# Generated by Django 4.2.16 on 2024-10-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonviewer',
            name='poke_type',
            field=models.CharField(choices=[('LE', 'Legendary'), ('EL', 'Electric'), ('GR', 'Grass'), ('PY', 'Psychic'), ('FI', 'Fire'), ('WR', 'Water'), ('AR', 'Air'), ('GH', 'Ghost')], default='', max_length=2),
        ),
    ]
