# Generated by Django 4.2.16 on 2024-10-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemonviewer_poke_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonviewer',
            old_name='image',
            new_name='pimage',
        ),
    ]
