# Generated by Django 4.2.16 on 2024-11-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_rename_image_pokemonviewer_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonviewer',
            name='discription',
            field=models.TextField(default=''),
        ),
    ]
