# Generated by Django 4.2.16 on 2024-11-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_pokemonviewer_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonviewer',
            old_name='discription',
            new_name='description',
        ),
    ]
