# Generated by Django 4.2.16 on 2024-11-03 07:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0005_rename_discription_pokemonviewer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
                ('poke_in_my_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemonviewer')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('poke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemonviewer')),
                ('poke_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery_date', models.DateTimeField(default=datetime.datetime(2024, 11, 3, 7, 56, 26, 641000, tzinfo=datetime.timezone.utc))),
                ('disc_cert', models.CharField(max_length=10)),
                ('poke_discovered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemonviewer')),
            ],
        ),
    ]
