# Generated by Django 4.2.16 on 2024-11-03 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_pokemonregion_pokemonrating_pokemondiscovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemondiscovery',
            name='discovery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 9, 43, 17, 879368, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pokemondiscovery',
            name='poke_discovered',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disc', to='pokemon.pokemonviewer'),
        ),
        migrations.AlterField(
            model_name='pokemonrating',
            name='poke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='pokemon.pokemonviewer'),
        ),
        migrations.RemoveField(
            model_name='pokemonregion',
            name='poke_in_my_region',
        ),
        migrations.AddField(
            model_name='pokemonregion',
            name='poke_in_my_region',
            field=models.ManyToManyField(related_name='region', to='pokemon.pokemonviewer'),
        ),
    ]
