# Generated by Django 4.2.16 on 2024-11-03 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_alter_pokemondiscovery_discovery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemondiscovery',
            name='discovery_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 3, 9, 48, 2, 678031, tzinfo=datetime.timezone.utc)),
        ),
    ]
