# Generated by Django 4.2.16 on 2024-11-16 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMS_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=15, verbose_name='Last Name')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('address', models.TextField(max_length=300, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=6, verbose_name='Zip Code')),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('web', models.URLField(verbose_name='Website')),
                ('email_address', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('manager', models.CharField(max_length=60, verbose_name='Manager')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('attendees', models.ManyToManyField(blank=True, to='ems.ems_user')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.venue')),
            ],
        ),
    ]
